name: Build

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  ZIG_VERSION: 0.14.0

jobs:
  build_linux_x86_64:
    name: Linux x86-64
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies (via apt)
        run: sudo apt update && sudo apt install -y libxkbcommon-dev xorg-dev libgtk-3-dev pkg-config
      - name: Install Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Build
        run: zig build
      - name: Debian package
        run: zig build deb
  build_linux_arm64:
    name: Linux ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies (via apt)
        run: sudo apt update && sudo apt install -y libxkbcommon-dev xorg-dev libgtk-3-dev pkg-config
      - name: Install Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Build
        run: zig build
      - name: Debian package
        run: zig build deb
  build_linux_x86_64_nix:
    name: Linux x86-64 (Nix)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v27
      - name: Build and run examples
        run: nix build .
  build_macos_arm64:
    name: macOS ARM64
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Build
        run: zig build
